name: Copy build output to repo - timthedev07.github.io
on:
  push:
    # branches:
    #   - release

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
      - name: List Files
        run: ls
      - name: Push output.
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source_file: "out/**/*"
          destination_repo: "timthedev07/timthedev07.github.io"
          user_email: ${{ secrets.EMAIL }}
          user_name: "timthedev07"
          commit_message: "New Static files built on github actions"
